<a href="https://colab.research.google.com/github/sundaybest3/txtanalysis/blob/main/frequency.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import re

# 1️⃣ GitHub CSV 파일 불러오기
url = "https://raw.githubusercontent.com/sundaybest3/txtanalysis/refs/heads/rawdata/High%20School%20Textbook%20Dialogue%20data_first%20analysis.xlsx.csv"
df = pd.read_csv(url)

# 2️⃣ 분석할 열 지정 (예: script 열)
column_name = "Script"

# 결측값 제거
texts = df[column_name].dropna().astype(str)

# 3️⃣ 전체 텍스트 합치기
full_text = " ".join(texts)

# 4️⃣ 전체 단어 수 계산
words = re.findall(r'\b\w+\b', full_text.lower())
total_word_count = len(words)

# 5️⃣ but 등장 횟수 계산 (대소문자 구분 없음)
but_count = len(re.findall(r'\bbut\b', full_text.lower()))

# 6️⃣ per 10,000 words 기준 빈도 계산
normalized_frequency = (but_count / total_word_count) * 10000

# 7️⃣ 결과 출력
print("Total word count:", total_word_count)
print("Frequency of 'but':", but_count)
print("Frequency per 10,000 words:", round(normalized_frequency, 1))

Total word count: 30784
Frequency of 'but': 158
Frequency per 10,000 words: 51.3

In [ ]:
import re

# 'but'이(가) 나타나는 모든 경우를 찾아서 주변 텍스트와 함께 출력합니다.
# 대소문자를 구분하지 않기 위해 full_text를 소문자로 변환합니다.
search_text = full_text.lower()

# 'but'이(가) 나타나는 모든 위치를 찾습니다.
# 정규 표현식 r'\bbut\b'는 독립적인 단어 'but'을 찾습니다.
matches = list(re.finditer(r'\bbut\b', search_text))

print(f"'but' 단어의 총 {len(matches)}개의 발생을 찾았습니다:\n")

# 각 'but'의 발생과 그 주변 텍스트를 출력합니다.
context_length = 50  # 'but' 단어의 앞뒤로 50글자의 맥락을 보여줍니다.

for i, match in enumerate(matches):
    start_index = match.start()
    end_index = match.end()

    # 'but' 단어 앞의 맥락을 가져옵니다.
    start_context = max(0, start_index - context_length)
    before_but = full_text[start_context:start_index]

    # 'but' 단어 뒤의 맥락을 가져옵니다.
    end_context = min(len(full_text), end_index + context_length)
    after_but = full_text[end_index:end_context]

    # 'but' 단어 자체는 원본 텍스트에서 가져옵니다 (대소문자 유지).
    original_but = full_text[start_index:end_index]

    print(f"[{i+1}] ...{before_but}**{original_but}**{after_but}...")
    print("--------------------------------------------------")

'but' 단어의 총 158개의 발생을 찾았습니다:

[1] ...t you’re using your phone too much.  I know, Mom, **but** I use it only for what I need to do.  You mean, w...
--------------------------------------------------
[2] ...le mental pressure and maintain balance.  I know, **but** I’m not sure where to start.  Well, how about cre...
--------------------------------------------------
[3] ....   I guess that makes sense. I’ll give it a try! **But** what about dealing with daily stresses?   You can...
--------------------------------------------------
[4] ...s location. It shows the student’s name at school **but** hides it outside of chool.  How does it work?  Th...
--------------------------------------------------
[5] ...g about the Foldscope, I searched for other small **but** creative items that help people in need.  It’s li...
--------------------------------------------------
[6] ...Hey! I’m working on an essay about my future job, **but** I’m not sure what I want to do. What about you?  ...
--------------------------------------------------
[7] ...n’t really improve their intelligence and talent. **But** people with a growth mindset think they can devel...
--------------------------------------------------
[8] ...nging, and it’s been my dream to become a singer. **But** every time I step onto the stage, I get incredibl...
--------------------------------------------------
[9] ...who share my passion.  I haven’t considered that, **but** I’ll give it a try. Thank you so much for the enc...
--------------------------------------------------
[10] ...k and determination. It may not happen overnight. **But** keep trying and believe in yourself, and you’ll a...
--------------------------------------------------
[11] ... me reflect on myself. I buy lots of clothes too, **but** I always feel like I have nothing to wear.  Well,...
--------------------------------------------------
[12] ...deep breath? That sounds too simple.  It’s simple **but** powerful. Trust me.  I’ll try that the next time....
--------------------------------------------------
[13] ...ld animals. They looked awesome!   I read it too. **But** they were all found to be fake.   What? Are you s...
--------------------------------------------------
[14] ...th the Nova17 and the O25 have massive batteries. **But** when used for a long time, the Nova17’s body gets...
--------------------------------------------------
[15] ...s before.   Really? It might sound a bit strange, **but** you’ll find it quite satisfying.   Can you tell m...
--------------------------------------------------
[16] ...ven more interesting is that this is a cold dish, **but** it’s something Koreans traditionally eat no matte...
--------------------------------------------------
[17] ...gning hanbok?   I get ideas from various sources, **but** my designs often begin with the idea of keeping t...
--------------------------------------------------
[18] ... think of that opinion?   I understand the worry, **but** I strongly believe that tradition isn’t fixed. It...
--------------------------------------------------
[19] ...ng. Transforming hanbok isn’t breaking tradition, **but** it is updating tradition. Hanbok can connect our ...
--------------------------------------------------
[20] ...refers to people who made important contributions **but** are not widely recognized.  Who are some examples...
--------------------------------------------------
[21] ... adopt AI too much, people can lose their jobs.   **But** AI can create new job opportunities in various fi...
--------------------------------------------------
[22] ...ne learning, and so on.   You have a point there, **but** I’m more concerned than excited when it comes to ...
--------------------------------------------------
[23] ... interesting.  Oh, I’m glad that you enjoyed it.  **But** I want to know more about the topic.  What do you...
--------------------------------------------------
[24] ...commended daily amount of caffeine?  No, I’m not. **But** I only drink two per day.  Well, just 2.5 mg of c...
--------------------------------------------------
[25] ...ould only have about 150 mg of caffeine per day.  **But** each of those energy drinks contains 120 mg.  Oh ...
--------------------------------------------------
[26] ...is going to be a fire drill today.  That’s right. **But** I’m a bit worried. I hurt my leg during our last ...
--------------------------------------------------
[27] ...ay party for my friend. I thought she’d be happy, **but** she looked a bit upset.  Oh, did you get the day ...
--------------------------------------------------
[28] ...he tag says it is made of 100% natural materials. **But** I wonder if it’s really eco-friendly.  Do you thi...
--------------------------------------------------
[29] ...gases are released during the production process, **but** the company doesn’t talk about that.  I think it ...
--------------------------------------------------
[30] ... your presentation is next week, isn’t it?   Yes, **but** I’m nervous. I’m not good at speaking in front of...
--------------------------------------------------
[31] ...d at speaking in front of others.   I understand. **But** if you want to overcome your fears, you must get ...
--------------------------------------------------
[32] ... it?  There are about one million insect species. **But** only 0.5 percent of them cause damage to crops. M...
--------------------------------------------------
[33] ...ose from.   Well, they are definitely convenient. **But** I worry about the excessive use of plastic packag...
--------------------------------------------------
[34] ...ave club meetings to attend and schoolwork to do, **but** I want some time with my friends, too!  I underst...
--------------------------------------------------
[35] ...nt some time with my friends, too!  I understand, **but** you should focus on important tasks first. How ab...
--------------------------------------------------
[36] ...ion of national treasures. They were taken abroad **but** have now been returned to Korea.  That’s interest...
--------------------------------------------------
[37] ... It was originally designed for wheelchair users, **but** it benefits others, too.  I’m surprised that it w...
--------------------------------------------------
[38] ...terested. Not only does it benefit the teenagers, **but** it also creates harmony within the community.  He...
--------------------------------------------------
[39] ...ted in communicating with younger people like me, **but** I was wrong.  Could you explain what you mean?  W...
--------------------------------------------------
[40] ...w you practiced a lot. You are going to do great. **But** I get nervous talking in front of many people. I ...
--------------------------------------------------
[41] ...eep breath before you speak. I tried that before, **but** it wasn’t really helpful. Then w hat a bout makin...
--------------------------------------------------
[42] ...I help you? It’s been a month since I moved here, **but** I’m not adjusting well to my new school. I’m sorr...
--------------------------------------------------
[43] ...elaxing and calming. Don’t you agree? I guess so, **but** isn’t it music for older people? Actually, it app...
--------------------------------------------------
[44] ...t the museum with Katie. Sounds like a good plan. **But** I’m worried because I often disagree with her. We...
--------------------------------------------------
[45] ...g your phone away for an hour each day? I’ll try, **but** I’m worried I’ll get bored. Then why don’t you tr...
--------------------------------------------------
[46] ... prefer to work alone. I understand how you feel, **but** sometimes studying in a group can be an effective...
--------------------------------------------------
[47] ...volunteering because it was a school requirement, **but** now I’m doing it because I want to. It’s so rewar...
--------------------------------------------------
[48] ...hought about doing volunteer work? Actually, yes. **But** I’m not sure what kind of volunteer work I could ...
--------------------------------------------------
[49] ...s to get inspiration. That would definitely help. **But** make sure you don’t copy their content! Good poin...
--------------------------------------------------
[50] ...ry skilled artist. AI might have good techniques, **but** you must admit that it lacks creativity. I see yo...
--------------------------------------------------
[51] ...admit that it lacks creativity. I see your point, **but** I believe AI is changing the way art is created. ...
--------------------------------------------------
[52] ...ve been working on that group project with Brian, **but** I’ve been having some problems.  Oh, no. I though...
--------------------------------------------------
[53] ...ind of problems? I thought we were getting along, **but** he’s not really doing his fair share. We have to ...
--------------------------------------------------
[54] ...hare. We have to hand in our project in two days, **but** he hasn’t finished his work. I’m really stressed ...
--------------------------------------------------
[55] ...h, yes, I remember. We had a lot of things to do, **but** all the members were such a good team, and really...
--------------------------------------------------
[56] ..., and really friendly, too. It was very demanding **but** ultimately a rewarding experience. We were both p...
--------------------------------------------------
[57] ... in science fiction. Let me check. Oh, I’m sorry, **but** it’s already been checked out.  That’s a shame. D...
--------------------------------------------------
[58] ...stories and express emotions just like novels do, **but** they just do so in a different way. But sometimes...
--------------------------------------------------
[59] ...ovels do, but they just do so in a different way. **But** sometimes they’re so unclear and hard to understa...
--------------------------------------------------
[60] ...to figure out the message.  I know what you mean, **but** that’s what makes poetry beautiful. There’s no ri...
--------------------------------------------------
[61] ...g fun of someone. I know, it does look like that, **but** she’s actually just saying hi. In certain regions...
--------------------------------------------------
[62] ...gues when they met someone new.  Oh, interesting. **But** isn’t sticking out tongues considered a bit rude ...
--------------------------------------------------
[63] ...it rude in some cultures, like ours? That’s true, **but** not in Tibet. So, if you ever visit Tibet, make s...
--------------------------------------------------
[64] ... What’s on your mind? Well, this may sound silly, **but** I wonder why we have two holes in our noses. Oh, ...
--------------------------------------------------
[65] ...y help us breathe and improve our sense of smell. **But** why do we need two holes? Wouldn’t it be better t...
--------------------------------------------------
[66] ...ive right now. I mean, one of the openings rests, **but** not fully. So, it keeps doing essential functions...
--------------------------------------------------
[67] ...during the 1980s. Really? That sounds incredible! **But** was it just a model house, or did she actually li...
--------------------------------------------------
[68] ...eautiful because of its green color. That’s true. **But** Dad, I wonder why the sea sometimes looks green l...
--------------------------------------------------
[69] ...osystem.  Oh, I had no idea there was such a day! **But** I read somewhere that bees are endangered.  Unfor...
--------------------------------------------------
[70] ...take a look.  Hmm, it seems to be rising steadily **but** with some ups and downs.  Yes, the rising sea lev...
--------------------------------------------------
[71] ...ied about its impact on the future of our planet. **But** today, I have some good news to share! According ...
--------------------------------------------------
[72] ...Well, I wanted to cook something for the elderly, **but** there are enough volunteers for cooking. So, I’ve...
--------------------------------------------------
[73] ...long? Absolutely! Why not? I’m not a good singer, **but** I’ll do my best! Great. I’ll pick you up at 10. H...
--------------------------------------------------
[74] ...g of bringing something that I don’t use anymore, **but** I’m not quite sure yet. What about you? Well, I’v...
--------------------------------------------------
[75] ..., I’ve had a look around my room for used things, **but** everything is too worn out. So, I’m thinking of b...
--------------------------------------------------
[76] ...e rewarding. You’ll not only help out the charity **but** also promote Korean culture. That’s right! I’m re...
--------------------------------------------------
[77] ... They are all loose-fitting. Hmm. They look good, **but** I think cotton is more comfortable than wool. In ...
--------------------------------------------------
[78] ...t. How much is it?  It was originally 50 dollars, **but** it’s 20% off right now. Plus, if you download our...
--------------------------------------------------
[79] ...e from your mom a couple of days ago? Yes, I did, **but** I ended up buying this really cool T-shirt becaus...
--------------------------------------------------
[80] ...things just because they’re on sale. I know, Dad, **but** I just love the design. I know you do, but you sh...
--------------------------------------------------
[81] ..., Dad, but I just love the design. I know you do, **but** you shouldn’t shop so carelessly. You need to mak...
--------------------------------------------------
[82] ...I agree! I think comedy acting is very difficult, **but** he did a great job. Absolutely! I’m even thinking...
--------------------------------------------------
[83] ... Hmm, I don’t like watching the same movie twice, **but** I definitely want to see more movies with that ac...
--------------------------------------------------
[84] ...ed that dancheong is not only used for decoration **but** also protects the buildings from bad weather and ...
--------------------------------------------------
[85] ...entrance if you’d like. Oh, sorry, I had no idea. **But** what if it rains later on? I heard that it might ...
--------------------------------------------------
[86] ...ncert tonight. Me, too! I’ve always loved Mozart, **but** I’ve never seen a live classical performance befo...
--------------------------------------------------
[87] ...o dress up? You don’t want to dress too casually, **but** you don’t have to dress too formally, either. Oka...
--------------------------------------------------
[88] ...re going to Italy next week! Yes, I’m so excited, **but** I’m worried about ordering food. What if the menu...
--------------------------------------------------
[89] ...eatures, too. My glasses don’t have this feature, **but** some of them can even take 3D photos. Technology ...
--------------------------------------------------
[90] ...ve a lot longer in the future then. That’s right. **But** we still have a long way to go. I believe there w...
--------------------------------------------------
[91] ...ame here. I’ve been trying to register for hours, **but** there seems to be something wrong.  We need to do...
--------------------------------------------------
[92] ...ce to explore the cafeteria or the gym?  Not yet, **but** I’m thinking of checking out the gym tomorrow.   ...
--------------------------------------------------
[93] ...n for tomorrow?   I’ve been working on my script, **but** I’m stuck. It’s incredibly annoying.  I feel the ...
--------------------------------------------------
[94] ...ng scripts is a lot of work. I’m almost finished, **but** I feel like it’s too long.  Mind if I take a look...
--------------------------------------------------
[95] ... Of course not. Here it is.  It looks good to me. **But** why don’t you add more images to your slides?  Go...
--------------------------------------------------
[96] ...e stretches.  That’s a great idea! I’ll join you, **but** I don’t know what to do.  Stand up and just follo...
--------------------------------------------------
[97] ...u were looking forward to joining a club.  I was, **but** none of the clubs caught my eye. In fact, I’m thi...
--------------------------------------------------
[98] ...here.  I was thinking of joining the hiking club, **but** I will sign up for yours instead!  I can’t believ...
--------------------------------------------------
[99] ...ich. It’s called banh mi.  A Vietnamese sandwich? **But** it looks like French bread!  It is. It’s a French...
--------------------------------------------------
[100] ... could say that. Do you want to try it?   Thanks, **but** I am not very adventurous with food. I prefer my ...
--------------------------------------------------
[101] ...my sauce called Alfredo sauce.  That sounds good, **but** I’m not a big fan of creamy sauces. I prefer some...
--------------------------------------------------
[102] ...ordered it.  It looks really good.  It sure does. **But** it looks like it may be a bit too spicy for me. I...
--------------------------------------------------
[103] ...tion. Is it recognized internationally?  Not yet, **but** I’m sure other countries will follow suit. There’...
--------------------------------------------------
[104] ...e banana peel? It’ll break down, won’t it?  Yeah, **but** it’s not good for the forest or the animals. You ...
--------------------------------------------------
[105] ...eally lucky to live near the ocean.  Yes, we are. **But** you need to be careful when you swim in the ocean...
--------------------------------------------------
[106] ...the high school cartoon character contest?  Yeah. **But** I don’t know the details. Do you know what the th...
--------------------------------------------------
[107] ...oing to draw a red panda.  Those are really cute. **But** are they endangered?  Yes, they’re seriously enda...
--------------------------------------------------
[108] ...ice beds in the rooms. Can you imagine that?  No. **But** it would be just as cool as sleeping in a tree. Y...
--------------------------------------------------
[109] ...o sports.  I’m interested in all kinds of sports, **but** basketball is my favorite. What about you?  I’m n...
--------------------------------------------------
[110] ...ite. What about you?  I’m not really into sports, **but** I’m interested in photography. I take photos of e...
--------------------------------------------------
[111] ...s.  How old are the artworks usually?  It varies, **but** a recent work I worked on was a painting of an It...
--------------------------------------------------
[112] ...ome an art restorer?  It requires diverse skills, **but** most importantly, you’re expected to have a scien...
--------------------------------------------------
[113] ...ings, so I want to study architecture in college. **But** I don’t know if I should study architectural desi...
--------------------------------------------------
[114] ...m.  Thanks. I heard you show rare classic movies, **but** I can’t find the schedule on your website.  We ar...
--------------------------------------------------
[115] ...ner photography class. There are spots available, **but** you’re expected to bring your own camera.  I see....
--------------------------------------------------
[116] ...Italy.  Exactly. They both involve wearing masks, **but** the cultural significance is quite different.  In...
--------------------------------------------------
[117] ...stay here in Seoul?  Yes. The city is so exciting **but** coming from Kuwait, I’m surprised that there are ...
--------------------------------------------------

In [ ]:
import pandas as pd

# 결과를 저장할 리스트 초기화
but_occurrences_data = []

# 각 'but'의 발생과 그 주변 텍스트를 추출하여 리스트에 추가합니다.
for i, match in enumerate(matches):
    start_index = match.start()
    end_index = match.end()

    # 'but' 단어 앞의 맥락을 가져옵니다.
    start_context = max(0, start_index - context_length)
    before_but = full_text[start_context:start_index]

    # 'but' 단어 뒤의 맥락을 가져옵니다.
    end_context = min(len(full_text), end_index + context_length)
    after_but = full_text[end_index:end_context]

    # 'but' 단어 자체는 원본 텍스트에서 가져옵니다 (대소문자 유지).
    original_but = full_text[start_index:end_index]

    but_occurrences_data.append({
        'occurrence_number': i + 1,
        'before_but': before_but,
        'but_word': original_but,
        'after_but': after_but,
        'full_context': f"...{before_but}**{original_but}**{after_but}..."
    })

# 리스트를 데이터프레임으로 변환
df_but_occurrences = pd.DataFrame(but_occurrences_data)

# CSV 파일로 저장
output_filename = 'but_occurrences.csv'
df_but_occurrences.to_csv(output_filename, index=False, encoding='utf-8')

print(f"'{output_filename}' 파일에 'but' 발생 정보가 저장되었습니다.")

# 저장된 데이터프레임의 첫 5행을 출력하여 확인
display(df_but_occurrences.head())

'but_occurrences.csv' 파일에 'but' 발생 정보가 저장되었습니다.

,occurrence_number,before_but,but_word,after_but,full_context
0,1,"t you’re using your phone too much. I know, M...",but,I use it only for what I need to do. You mea...,...t you’re using your phone too much. I know...
1,2,le mental pressure and maintain balance. I kn...,but,"I’m not sure where to start. Well, how about...",...le mental pressure and maintain balance. I...
2,3,. I guess that makes sense. I’ll give it a t...,But,what about dealing with daily stresses? You...,.... I guess that makes sense. I’ll give it ...
3,4,s location. It shows the student’s name at sch...,but,hides it outside of chool. How does it work?...,...s location. It shows the student’s name at ...
4,5,"g about the Foldscope, I searched for other sm...",but,creative items that help people in need. It’...,"...g about the Foldscope, I searched for other..."

In [ ]:
import pandas as pd
import re

# 1️⃣ GitHub CSV 파일 불러오기
url = "https://raw.githubusercontent.com/sundaybest3/txtanalysis/refs/heads/refineddata/cleaned_sbcase_56.csv"
df = pd.read_csv(url, sep='\t')

# 2️⃣ 분석할 열 지정 (예: script 열)
column_name = "script"

# 결측값 제거
texts = df[column_name].dropna().astype(str)

# 3️⃣ 전체 텍스트 합치기
full_text = " ".join(texts)

# 4️⃣ 전체 단어 수 계산
words = re.findall(r'\b\w+\b', full_text.lower())
total_word_count = len(words)

# 5️⃣ but 등장 횟수 계산 (대소문자 구분 없음)
but_count = len(re.findall(r'\bbut\b', full_text.lower()))

# 6️⃣ per 10,000 words 기준 빈도 계산
normalized_frequency = (but_count / total_word_count) * 10000

# 7️⃣ 결과 출력
print("Total word count:", total_word_count)
print("Frequency of 'but':", but_count)
print("Frequency per 10,000 words:", round(normalized_frequency, 1))

Total word count: 7069
Frequency of 'but': 56
Frequency per 10,000 words: 79.2

In [ ]:
import pandas as pd
import re

# 1️⃣ 데이터 불러오기
url = "https://raw.githubusercontent.com/sundaybest3/txtanalysis/refs/heads/rawdata/High%20School%20Textbook%20Dialogue%20data_first%20analysis_2.xlsx.csv"
df = pd.read_csv(url)

# 2️⃣ 열 이름 정리
df.columns = df.columns.str.strip()

# 3️⃣ 필요한 열 선택
df = df[['Label', 'Script']].copy()

# 4️⃣ 결측값 처리
df['Script'] = df['Script'].fillna('').astype(str)

# 5️⃣ apostrophe 두 종류 모두 포함한 word count 계산
df['word_count'] = df['Script'].apply(
    lambda x: len(re.findall(r"[A-Za-z]+(?:['’][A-Za-z]+)?", x))
)

# 6️⃣ but 등장 횟수 계산
df['but_frequency'] = df['Script'].str.lower().str.count(r'\bbut\b')

# 7️⃣ 교과서별 집계
result = df.groupby('Label', as_index=False).agg(
    total_words=('word_count', 'sum'),
    but_frequency=('but_frequency', 'sum')
)

# 8️⃣ per 10,000 words 계산
result['per_10000_words'] = (
    result['but_frequency'] /
    result['total_words'] * 10000
).round(1)

# 9️⃣ 정렬
result = result.sort_values('Label')

# 🔟 전체 합계 계산
total_words_sum = result['total_words'].sum()
but_frequency_sum = result['but_frequency'].sum()

total_row = pd.DataFrame({
    'Label': ['TOTAL'],
    'total_words': [total_words_sum],
    'but_frequency': [but_frequency_sum],
    'per_10000_words': [
        round((but_frequency_sum / total_words_sum) * 10000, 1)
    ]
})

# 11️⃣ 합계 행 추가
result = pd.concat([result, total_row], ignore_index=True)

# 12️⃣ 결과 출력
print(result)

    Label  total_words  but_frequency  per_10000_words
0      A1         1494              3             20.1
1      A2         1489              6             40.3
2      B1         1352              5             37.0
3      B2         1080              6             55.6
4      C1          585              5             85.5
5      C2          970              7             72.2
6      D1         1185              2             16.9
7      D2         1500              9             60.0
8      E1         2450             20             81.6
9      E2         2171             19             87.5
10     F1          917              4             43.6
11     F2          979              3             30.6
12     G1         1139              4             35.1
13     G2         1260              6             47.6
14     H1         2478             18             72.6
15     H2         2827             19             67.2
16     J1         1749              9             51.5
17     J2         1745              8             45.8
18     K1         1069              0              0.0
19     K2          937              5             53.4
20  TOTAL        29376            158             53.8

In [ ]:
import pandas as pd
import re

url = "https://raw.githubusercontent.com/sundaybest3/txtanalysis/refs/heads/rawdata/High%20School%20Textbook%20Dialogue%20data_first%20analysis_2.xlsx.csv"
df = pd.read_csv(url)

df.columns = df.columns.str.strip()
df = df[['Label', 'Script']].copy()
df['Script'] = df['Script'].fillna('').astype(str)

# 하이픈과 apostrophe를 단어 내부 요소로 허용
def count_words(text):
    tokens = re.findall(r"[A-Za-z]+(?:[-’'][A-Za-z]+)*", text)
    return len(tokens)

df['word_count'] = df['Script'].apply(count_words)
df['but_frequency'] = df['Script'].str.lower().str.count(r'\bbut\b')

result = df.groupby('Label', as_index=False).agg(
    total_words=('word_count', 'sum'),
    but_frequency=('but_frequency', 'sum')
)

result['per_10000_words'] = (
    result['but_frequency'] / result['total_words'] * 10000
).round(1)

result = result.sort_values('Label')

total_row = pd.DataFrame({
    'Label': ['TOTAL'],
    'total_words': [result['total_words'].sum()],
    'but_frequency': [result['but_frequency'].sum()],
    'per_10000_words': [round(result['but_frequency'].sum() / result['total_words'].sum() * 10000, 1)]
})

result = pd.concat([result, total_row], ignore_index=True)

print(result)

    Label  total_words  but_frequency  per_10000_words
0      A1         1493              3             20.1
1      A2         1489              6             40.3
2      B1         1350              5             37.0
3      B2         1080              6             55.6
4      C1          585              5             85.5
5      C2          969              7             72.2
6      D1         1177              2             17.0
7      D2         1499              9             60.0
8      E1         2440             20             82.0
9      E2         2160             19             88.0
10     F1          917              4             43.6
11     F2          975              3             30.8
12     G1         1138              4             35.1
13     G2         1259              6             47.7
14     H1         2476             18             72.7
15     H2         2821             19             67.4
16     J1         1737              9             51.8
17     J2         1735              8             46.1
18     K1         1065              0              0.0
19     K2          936              5             53.4
20  TOTAL        29301            158             53.9

In [ ]:
import pandas as pd
import re

# 1️⃣ 데이터 불러오기
url = "https://raw.githubusercontent.com/sundaybest3/txtanalysis/refs/heads/rawdata/High%20School%20Textbook%20Dialogue%20data_first%20analysis.xlsx.csv"
df = pd.read_csv(url)

# 2️⃣ 열 이름 정리
df.columns = df.columns.str.strip()

# 3️⃣ 필요한 열 선택
df = df[['Label', 'Script']].copy()

# 4️⃣ 결측값 처리
df['Script'] = df['Script'].fillna('').astype(str)

# 5️⃣ corpus-style word count 계산
# contraction 유지 (don't, I'm 등 1단어 처리)
df['word_count'] = df['Script'].apply(
    lambda x: len(re.findall(r"[A-Za-z]+(?:'[A-Za-z]+)?", x))
)

# 6️⃣ but 등장 횟수 계산
df['but_frequency'] = df['Script'].str.lower().str.count(r'\bbut\b')

# 7️⃣ 교과서별 집계
result = df.groupby('Label', as_index=False).agg(
    total_words=('word_count', 'sum'),
    but_frequency=('but_frequency', 'sum')
)

# 8️⃣ per 10,000 words 계산
result['per_10000_words'] = (
    result['but_frequency'] /
    result['total_words'] * 10000
).round(1)

# 9️⃣ 정렬
result = result.sort_values('Label')

# 🔟 전체 합계 계산
total_words_sum = result['total_words'].sum()
but_frequency_sum = result['but_frequency'].sum()

total_row = pd.DataFrame({
    'Label': ['TOTAL'],
    'total_words': [total_words_sum],
    'but_frequency': [but_frequency_sum],
    'per_10000_words': [
        round((but_frequency_sum / total_words_sum) * 10000, 1)
    ]
})

# 11️⃣ 합계 행 추가
result = pd.concat([result, total_row], ignore_index=True)

# 12️⃣ 결과 출력
print(result)

    Label  total_words  but_frequency  per_10000_words
0      A1         1494              3             20.1
1      A2         1489              6             40.3
2      B1         1352              5             37.0
3      B2         1080              6             55.6
4      C1          585              5             85.5
5      C2          970              7             72.2
6      D1         1185              2             16.9
7      D2         1500              9             60.0
8      E1         2450             20             81.6
9      E2         2171             19             87.5
10     F1          917              4             43.6
11     F2          979              3             30.6
12     G1         1139              4             35.1
13     G2         1260              6             47.6
14     H1         2478             18             72.6
15     H2         2827             19             67.2
16     J1         1749              9             51.5
17     J2         1745              8             45.8
18     K1         1070              0              0.0
19     K2          937              5             53.4
20  TOTAL        29377            158             53.8

In [ ]:
# 결과를 CSV 파일로 저장
output_filename_summary = 'but_frequency_summary_by_textbook.csv'
result.to_csv(output_filename_summary, index=False, encoding='utf-8')

print(f"'{output_filename_summary}' 파일에 교과서별 'but' 빈도 분석 결과가 저장되었습니다.")

# 저장된 데이터프레임의 첫 5행을 출력하여 확인
display(result.head())

'but_frequency_summary_by_textbook.csv' 파일에 교과서별 'but' 빈도 분석 결과가 저장되었습니다.

  Label  total_words  but_frequency  per_10000_words
0    A1         1568              3             19.1
1    A2         1564              6             38.4
2    B1         1424              5             35.1
3    B2         1123              6             53.4
4    C1          622              5             80.4